
version: '3.8'

services:
  balancer:
    container_name: balancer
    build:
      context: ./balancer
      dockerfile: Dockerfile
    hostname: balancer
    networks:
      micro:
        ipv4_address: 10.5.50.60
    privileged: true
    ports:
      - "80:80"

    restart: unless-stopped
    tty: true
    command: ln -s /etc/nginx/sites-available/vhost /etc/nginx/sites-enabled/vhost
    command: /usr/sbin/nginx -g "daemon off;"
  sessions:
    container_name: sessions_storage
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: express_sessions
      MONGO_INITDB_ROOT_USERNAME: sessions
      MONGO_INITDB_ROOT_PASSWORD: micro_sessions
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      micro:
        ipv4_address: 10.5.50.70
    restart: unless-stopped
    tty: true


  gateway_1:
    container_name: gateway_1
    build:
      context: ./gateway
    networks:
      micro:
        ipv4_address: 10.5.50.2
    working_dir: /app
    ports:
      - "3001:3001"
    command: node server.js 3001 "users"
    expose:
      - "3001"
      - "8000-8100"
  

  db_client_users:
    container_name: db_client_users
    build:
      context: ./database
    networks:
      micro:
        ipv4_address: 10.5.50.81
    working_dir: /app
    command: node database.js users 10.5.50.151

    expose:
      - "8000-8100"
  db_users:
    container_name: db_users
    image: mongo:latest
    networks:
      micro:
        ipv4_address: 10.5.50.151
    working_dir: /app

    expose:
      - "8000-8100"
  

volumes:
  mongodb_data_container:


networks:
#Internal-only network for proper nginx proxying and ssh
  micro:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.50.0/16

#External network actually
  default:
    driver: bridge

